# Generated by Django 3.2.7 on 2021-09-09 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='platform',
            new_name='rater',
        ),
        migrations.AddField(
            model_name='rate',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recommender.movie'),
            preserve_default=False,
        ),
    ]
