# Generated by Django 3.2.7 on 2021-09-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_auto_20210911_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='rater',
        ),
        migrations.RemoveField(
            model_name='rater',
            name='api_url',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
