# Generated by Django 3.2.7 on 2021-09-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_auto_20210911_1006'),
    ]

    operations = [
    ]
